### ISSUE TITLE
Add missing german translation

### ISSUE THREAD

**Issue by double2ugly** [akiko-pusu/redmine_issue_badge#110]
Feel free to add the german translation as written below...
I skipped the admin-portion of the translations...

```
# German strings go here for Rails i18n
de:
  title_issue_badge: Ticket Badge
  label_issue_badge: Anzahl der zugewiesenen Tickets anzeigen
  label_activate_for_all_users: Display issue badge for all users
  label_enabled_polling: Enabled pollig to refresh issue count（Interval 60sec）
  label_show_assigned_to_group: Tickets für zugewiesene Gruppen anzeigen
  label_badge_order: Liste sortieren
  label_badge_order_oldest: nach den ältesten 5 Tickets
  label_badge_order_newest: nach den neuesten 5 Tickets
```
